name: idea_board
description: An app for collecting ideas.
publish_to: 'none'
version: 2.1.1+9

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  sqflite:
  path:
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  tiktoklikescroller: ^0.2.3
  animations: ^2.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  sign_in_with_apple: ^6.1.0
  flutter_quill: ^9.3.6
  tuple: ^2.0.0
  shared_preferences: ^2.0.15

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/new_icon.png"
  min_sdk_android: 23


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
